#pragma once
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
namespace vulkanscope_registry {
inline constexpr const char* kBaseline = "Vulkan 1.4.357";
inline constexpr const char* kMode = "offline registry-driven validated runtime query catalog";
inline constexpr const char* kHeaderBaseline = "Vulkan 1.4.357 / official header baseline";
inline constexpr const char* kReportSchema = "4";
inline constexpr std::size_t kCatalogSchemaVersion = 6;
inline constexpr std::size_t kImplementedPhysicalDeviceStructCount = 76;
inline constexpr std::size_t kValidatedRuntimeQueryGroupCount = 57;
inline constexpr std::size_t kRuntimeExtensionTokenCount = 266;
inline constexpr std::array<const char*, 78> kImplementedPhysicalDeviceStructs = {
    "VkPhysicalDeviceComputeOccupancyPriorityFeaturesNV",
    "VkPhysicalDeviceCooperativeMatrixConversionFeaturesQCOM",
    "VkPhysicalDeviceCooperativeMatrixDecodeVectorFeaturesNV",
    "VkPhysicalDeviceCooperativeMatrixFeaturesKHR",
    "VkPhysicalDeviceCooperativeMatrixPropertiesKHR",
    "VkPhysicalDeviceDataGraphNeuralAcceleratorStatisticsFeaturesARM",
    "VkPhysicalDeviceDataGraphOpticalFlowFeaturesARM",
    "VkPhysicalDeviceDescriptorHeapFeaturesEXT",
    "VkPhysicalDeviceDescriptorHeapPropertiesEXT",
    "VkPhysicalDeviceDeviceAddressCommandsFeaturesKHR",
    "VkPhysicalDeviceElapsedTimerQueryFeaturesQCOM",
    "VkPhysicalDeviceExtendedFlagsFeaturesKHR",
    "VkPhysicalDeviceExternalBufferInfo",
    "VkPhysicalDeviceExternalFenceInfo",
    "VkPhysicalDeviceExternalImageFormatInfo",
    "VkPhysicalDeviceExternalSemaphoreInfo",
    "VkPhysicalDeviceFaultFeaturesKHR",
    "VkPhysicalDeviceFaultPropertiesKHR",
    "VkPhysicalDeviceFeatures",
    "VkPhysicalDeviceFeatures2",
    "VkPhysicalDeviceFragmentDensityMap2PropertiesEXT",
    "VkPhysicalDeviceFragmentDensityMapPropertiesEXT",
    "VkPhysicalDeviceGroupProperties",
    "VkPhysicalDeviceImageFormatInfo2",
    "VkPhysicalDeviceImageProcessing3FeaturesQCOM",
    "VkPhysicalDeviceInternallySynchronizedQueuesFeaturesKHR",
    "VkPhysicalDeviceLimits",
    "VkPhysicalDeviceMaintenance10FeaturesKHR",
    "VkPhysicalDeviceMaintenance10PropertiesKHR",
    "VkPhysicalDeviceMaintenance11FeaturesKHR",
    "VkPhysicalDeviceMaintenance7FeaturesKHR",
    "VkPhysicalDeviceMaintenance7PropertiesKHR",
    "VkPhysicalDeviceMaintenance8FeaturesKHR",
    "VkPhysicalDeviceMaintenance9FeaturesKHR",
    "VkPhysicalDeviceMaintenance9PropertiesKHR",
    "VkPhysicalDeviceMemoryBudgetPropertiesEXT",
    "VkPhysicalDeviceMemoryProperties",
    "VkPhysicalDeviceMemoryProperties2",
    "VkPhysicalDeviceMultisampledRenderToSwapchainFeaturesEXT",
    "VkPhysicalDeviceOpacityMicromapFeaturesKHR",
    "VkPhysicalDeviceOpacityMicromapPropertiesKHR",
    "VkPhysicalDevicePipelineBinaryFeaturesKHR",
    "VkPhysicalDevicePipelineBinaryPropertiesKHR",
    "VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC",
    "VkPhysicalDevicePresentId2FeaturesKHR",
    "VkPhysicalDevicePresentModeFifoLatestReadyFeaturesKHR",
    "VkPhysicalDevicePresentWait2FeaturesKHR",
    "VkPhysicalDevicePrimitiveRestartIndexFeaturesEXT",
    "VkPhysicalDeviceProperties2",
    "VkPhysicalDevicePushConstantBankFeaturesNV",
    "VkPhysicalDevicePushConstantBankPropertiesNV",
    "VkPhysicalDeviceQueuePerfHintFeaturesQCOM",
    "VkPhysicalDeviceQueuePerfHintPropertiesQCOM",
    "VkPhysicalDeviceShaderAbortFeaturesKHR",
    "VkPhysicalDeviceShaderAbortPropertiesKHR",
    "VkPhysicalDeviceShaderConstantDataFeaturesKHR",
    "VkPhysicalDeviceShaderInstrumentationFeaturesARM",
    "VkPhysicalDeviceShaderInstrumentationPropertiesARM",
    "VkPhysicalDeviceShaderLongVectorFeaturesEXT",
    "VkPhysicalDeviceShaderLongVectorPropertiesEXT",
    "VkPhysicalDeviceShaderMixedFloatDotProductFeaturesVALVE",
    "VkPhysicalDeviceShaderMultipleWaitQueuesFeaturesQCOM",
    "VkPhysicalDeviceShaderMultipleWaitQueuesPropertiesQCOM",
    "VkPhysicalDeviceShaderOCPMicroscalingTypesFeaturesEXT",
    "VkPhysicalDeviceShaderSplitBarrierFeaturesEXT",
    "VkPhysicalDeviceShaderSplitBarrierPropertiesEXT",
    "VkPhysicalDeviceShaderSubgroupPartitionedFeaturesEXT",
    "VkPhysicalDeviceShaderUniformBufferUnsizedArrayFeaturesEXT",
    "VkPhysicalDeviceSparseImageFormatInfo2",
    "VkPhysicalDeviceTextureCompressionASTC3DFeaturesEXT",
    "VkPhysicalDeviceThrottleHintFeaturesSEC",
    "VkPhysicalDeviceToolProperties",
    "VkPhysicalDeviceVideoEncodeFeedback2FeaturesKHR",
    "VkPhysicalDeviceVulkan11Properties",
    "VkPhysicalDeviceVulkan12Properties",
    "VkPhysicalDeviceVulkan13Properties",
    "VkPhysicalDeviceVulkan14Properties",
};
inline constexpr std::array<const char*, 57> kValidatedRuntimeQueryGroups = {
    "astc3D",
    "computeOccupancyPriority",
    "cooperativeMatrix",
    "cooperativeMatrixConversion",
    "cooperativeMatrixDecodeVector",
    "core11",
    "core12",
    "core13",
    "core14",
    "dataGraphNeuralAcceleratorStatistics",
    "dataGraphOpticalFlow",
    "descriptorHeap",
    "deviceAddressCommands",
    "deviceFault",
    "elapsedTimerQuery",
    "extendedFlags",
    "external",
    "fifoLatestReady",
    "format2",
    "fragmentDensityMap",
    "fragmentDensityMap2",
    "groups",
    "imageFormat2",
    "imageProcessing3",
    "internallySynchronizedQueues",
    "maintenance10",
    "maintenance11",
    "maintenance7",
    "maintenance8",
    "maintenance9",
    "memory2",
    "multisampledRenderToSwapchain",
    "opacityMicromap",
    "pipelineBinary",
    "pipelineCacheIncrementalMode",
    "presentId2",
    "presentWait2",
    "primitiveRestartIndex",
    "pushConstantBank",
    "queue2",
    "queuePerfHint",
    "shaderAbort",
    "shaderConstantData",
    "shaderInstrumentation",
    "shaderLongVector",
    "shaderMixedFloatDotProduct",
    "shaderMultipleWaitQueues",
    "shaderOcpMicroscalingTypes",
    "shaderSplitBarrier",
    "shaderSubgroupPartitioned",
    "shaderUniformBufferUnsizedArray",
    "sparse",
    "throttleHint",
    "tools",
    "videoEncodeFeedback2",
    "vulkan14",
    "videoCapabilities",
};
struct QueryDescriptor {
    const char* group;
    const char* scope;
    const char* extension;
    uint32_t minApiMinor;
    const char* queryKind;
};

inline constexpr std::array<QueryDescriptor, 57> kValidatedQueryDescriptors = {{
    {"astc3D", "device-extension", "VK_EXT_texture_compression_astc_3d", 0, "feature+property"},
    {"computeOccupancyPriority", "device-extension", "VK_NV_compute_occupancy_priority", 0, "feature+property"},
    {"cooperativeMatrix", "device-extension", "VK_KHR_cooperative_matrix", 0, "feature+property"},
    {"cooperativeMatrixConversion", "device-extension", "VK_QCOM_cooperative_matrix_conversion", 0, "feature+property"},
    {"cooperativeMatrixDecodeVector", "device-extension", "VK_NV_cooperative_matrix_decode_vector", 0, "feature+property"},
    {"core11", "core", "", 1, "feature+property"},
    {"core12", "core", "", 2, "feature+property"},
    {"core13", "core", "", 3, "feature+property"},
    {"core14", "core", "", 4, "feature+property"},
    {"dataGraphNeuralAcceleratorStatistics", "device-extension", "VK_ARM_data_graph_neural_accelerator_statistics", 0, "feature+property"},
    {"dataGraphOpticalFlow", "device-extension", "VK_ARM_data_graph_optical_flow", 0, "feature-only"},
    {"descriptorHeap", "device-extension", "VK_EXT_descriptor_heap", 0, "feature+property"},
    {"deviceAddressCommands", "device-extension", "VK_KHR_device_address_commands", 0, "feature-only"},
    {"deviceFault", "device-extension", "VK_KHR_device_fault", 0, "feature+property"},
    {"elapsedTimerQuery", "device-extension", "VK_QCOM_elapsed_timer_query", 0, "feature+property"},
    {"extendedFlags", "device-extension", "VK_KHR_extended_flags", 0, "feature-only"},
    {"external", "advanced", "", 0, "physical-device-query"},
    {"fifoLatestReady", "device-extension", "VK_KHR_present_mode_fifo_latest_ready", 0, "feature+property"},
    {"format2", "advanced", "", 0, "physical-device-query"},
    {"fragmentDensityMap", "device-extension", "VK_EXT_fragment_density_map", 0, "feature+property"},
    {"fragmentDensityMap2", "device-extension", "VK_EXT_fragment_density_map2", 0, "feature+property"},
    {"groups", "advanced", "", 0, "physical-device-query"},
    {"imageFormat2", "advanced", "", 0, "physical-device-query"},
    {"imageProcessing3", "device-extension", "VK_QCOM_image_processing3", 0, "feature+property"},
    {"internallySynchronizedQueues", "device-extension", "VK_KHR_internally_synchronized_queues", 0, "feature+property"},
    {"maintenance10", "device-extension", "VK_KHR_maintenance10", 0, "feature+property"},
    {"maintenance11", "device-extension", "VK_KHR_maintenance11", 0, "feature-only"},
    {"maintenance7", "device-extension", "VK_KHR_maintenance7", 0, "feature+property"},
    {"maintenance8", "device-extension", "VK_KHR_maintenance8", 0, "feature+property"},
    {"maintenance9", "device-extension", "VK_KHR_maintenance9", 0, "feature+property"},
    {"memory2", "advanced", "", 0, "physical-device-query"},
    {"multisampledRenderToSwapchain", "device-extension", "VK_EXT_multisampled_render_to_swapchain", 0, "feature+property"},
    {"opacityMicromap", "device-extension", "VK_KHR_opacity_micromap", 0, "feature+property"},
    {"pipelineBinary", "device-extension", "VK_KHR_pipeline_binary", 0, "feature+property"},
    {"pipelineCacheIncrementalMode", "device-extension", "VK_SEC_pipeline_cache_incremental_mode", 0, "feature-only"},
    {"presentId2", "device-extension", "VK_KHR_present_id2", 0, "feature+property"},
    {"presentWait2", "device-extension", "VK_KHR_present_wait2", 0, "feature+property"},
    {"primitiveRestartIndex", "device-extension", "VK_EXT_primitive_restart_index", 0, "feature+property"},
    {"pushConstantBank", "device-extension", "VK_NV_push_constant_bank", 0, "feature+property"},
    {"queue2", "advanced", "", 0, "physical-device-query"},
    {"queuePerfHint", "device-extension", "VK_QCOM_queue_perf_hint", 0, "feature+property"},
    {"shaderAbort", "device-extension", "VK_KHR_shader_abort", 0, "feature+property"},
    {"shaderConstantData", "device-extension", "VK_KHR_shader_constant_data", 0, "feature+property"},
    {"shaderInstrumentation", "device-extension", "VK_ARM_shader_instrumentation", 0, "feature+property"},
    {"shaderLongVector", "device-extension", "VK_EXT_shader_long_vector", 0, "feature+property"},
    {"shaderMixedFloatDotProduct", "device-extension", "VK_VALVE_shader_mixed_float_dot_product", 0, "feature+property"},
    {"shaderMultipleWaitQueues", "device-extension", "VK_QCOM_shader_multiple_wait_queues", 0, "feature+property"},
    {"shaderOcpMicroscalingTypes", "device-extension", "VK_EXT_shader_ocp_microscaling_types", 0, "feature-only"},
    {"shaderSplitBarrier", "device-extension", "VK_EXT_shader_split_barrier", 0, "feature+property"},
    {"shaderSubgroupPartitioned", "device-extension", "VK_EXT_shader_subgroup_partitioned", 0, "feature+property"},
    {"shaderUniformBufferUnsizedArray", "device-extension", "VK_EXT_shader_uniform_buffer_unsized_array", 0, "feature-only"},
    {"sparse", "advanced", "", 0, "physical-device-query"},
    {"throttleHint", "device-extension", "VK_SEC_throttle_hint", 0, "feature+property"},
    {"tools", "advanced", "", 0, "physical-device-query"},
    {"videoEncodeFeedback2", "device-extension", "VK_KHR_video_encode_feedback2", 0, "feature+property"},
    {"videoCapabilities", "advanced", "", 0, "video-profile+capabilities+formats"},
    {"vulkan14", "core", "", 4, "feature+property"},
}};

constexpr const QueryDescriptor* findQueryDescriptor(const char* group) {
    if (!group) return nullptr;
    for (const auto& descriptor : kValidatedQueryDescriptors) {
        if (std::strcmp(descriptor.group, group) == 0) return &descriptor;
    }
    return nullptr;
}

inline constexpr std::array<const char*, 10> kInstanceDependencyCandidates = {
    "VK_KHR_get_physical_device_properties2",
    "VK_KHR_get_surface_capabilities2",
    "VK_KHR_device_group_creation",
    "VK_KHR_external_memory_capabilities",
    "VK_KHR_external_semaphore_capabilities",
    "VK_KHR_external_fence_capabilities",
    "VK_KHR_display",
    "VK_KHR_get_display_properties2",
    "VK_EXT_debug_utils",
    "VK_EXT_debug_report",
};

}
