#pragma once
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
namespace vulkanscope_registry {
inline constexpr const char* kBaseline = "Vulkan 1.4.360";
inline constexpr const char* kMode = "offline registry-driven validated runtime query catalog";
inline constexpr const char* kHeaderBaseline = "Vulkan 1.4.360 compile headers; validated query catalog Vulkan 1.4.360";
inline constexpr const char* kReportSchema = "4";
inline constexpr std::size_t kCatalogSchemaVersion = 6;
inline constexpr std::size_t kImplementedPhysicalDeviceStructCount = 109;
inline constexpr std::size_t kValidatedRuntimeQueryGroupCount = 104;
inline constexpr std::size_t kRuntimeExtensionTokenCount = 268;
inline constexpr std::array<const char*, 109> kImplementedPhysicalDeviceStructs = {
    "VkPhysicalDeviceComputeOccupancyPriorityFeaturesNV",
    "VkPhysicalDeviceCooperativeMatrixConversionFeaturesQCOM",
    "VkPhysicalDeviceCooperativeMatrixDecodeVectorFeaturesNV",
    "VkPhysicalDeviceCooperativeMatrixFeaturesKHR",
    "VkPhysicalDeviceCooperativeMatrixPropertiesKHR",
    "VkPhysicalDeviceDataGraphNeuralAcceleratorStatisticsFeaturesARM",
    "VkPhysicalDeviceDataGraphOpticalFlowFeaturesARM",
    "VkPhysicalDeviceDescriptorHeapFeaturesEXT",
    "VkPhysicalDeviceDescriptorHeapPropertiesEXT",
    "VkPhysicalDeviceDeviceAddressCommandsFeaturesKHR",
    "VkPhysicalDeviceElapsedTimerQueryFeaturesQCOM",
    "VkPhysicalDeviceExtendedFlagsFeaturesKHR",
    "VkPhysicalDeviceExternalBufferInfo",
    "VkPhysicalDeviceExternalFenceInfo",
    "VkPhysicalDeviceExternalImageFormatInfo",
    "VkPhysicalDeviceExternalSemaphoreInfo",
    "VkPhysicalDeviceFaultFeaturesKHR",
    "VkPhysicalDeviceFaultPropertiesKHR",
    "VkPhysicalDeviceFeatures",
    "VkPhysicalDeviceFeatures2",
    "VkPhysicalDeviceFragmentDensityMap2PropertiesEXT",
    "VkPhysicalDeviceFragmentDensityMapPropertiesEXT",
    "VkPhysicalDeviceGroupProperties",
    "VkPhysicalDeviceImageFormatInfo2",
    "VkPhysicalDeviceImageProcessing3FeaturesQCOM",
    "VkPhysicalDeviceImageTilingControlFeaturesEXT",
    "VkPhysicalDeviceCooperativeMatrixMaintenance1FeaturesEXT",
    "VkPhysicalDeviceInternallySynchronizedQueuesFeaturesKHR",
    "VkPhysicalDeviceLimits",
    "VkPhysicalDeviceMaintenance10FeaturesKHR",
    "VkPhysicalDeviceMaintenance10PropertiesKHR",
    "VkPhysicalDeviceMaintenance11FeaturesKHR",
    "VkPhysicalDeviceMaintenance7FeaturesKHR",
    "VkPhysicalDeviceMaintenance7PropertiesKHR",
    "VkPhysicalDeviceMaintenance8FeaturesKHR",
    "VkPhysicalDeviceMaintenance9FeaturesKHR",
    "VkPhysicalDeviceMaintenance9PropertiesKHR",
    "VkPhysicalDeviceMemoryBudgetPropertiesEXT",
    "VkPhysicalDeviceMemoryProperties",
    "VkPhysicalDeviceMemoryProperties2",
    "VkPhysicalDeviceMultisampledRenderToSwapchainFeaturesEXT",
    "VkPhysicalDeviceOpacityMicromapFeaturesKHR",
    "VkPhysicalDeviceOpacityMicromapPropertiesKHR",
    "VkPhysicalDevicePipelineBinaryFeaturesKHR",
    "VkPhysicalDevicePipelineBinaryPropertiesKHR",
    "VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC",
    "VkPhysicalDevicePresentId2FeaturesKHR",
    "VkPhysicalDevicePresentModeFifoLatestReadyFeaturesKHR",
    "VkPhysicalDevicePresentWait2FeaturesKHR",
    "VkPhysicalDevicePrimitiveRestartIndexFeaturesEXT",
    "VkPhysicalDeviceProperties2",
    "VkPhysicalDevicePushConstantBankFeaturesNV",
    "VkPhysicalDevicePushConstantBankPropertiesNV",
    "VkPhysicalDeviceQueuePerfHintFeaturesQCOM",
    "VkPhysicalDeviceQueuePerfHintPropertiesQCOM",
    "VkPhysicalDeviceShaderAbortFeaturesKHR",
    "VkPhysicalDeviceShaderAbortPropertiesKHR",
    "VkPhysicalDeviceShaderConstantDataFeaturesKHR",
    "VkPhysicalDeviceShaderInstrumentationFeaturesARM",
    "VkPhysicalDeviceShaderInstrumentationPropertiesARM",
    "VkPhysicalDeviceShaderLongVectorFeaturesEXT",
    "VkPhysicalDeviceShaderLongVectorPropertiesEXT",
    "VkPhysicalDeviceShaderMixedFloatDotProductFeaturesVALVE",
    "VkPhysicalDeviceShaderMultipleWaitQueuesFeaturesQCOM",
    "VkPhysicalDeviceShaderMultipleWaitQueuesPropertiesQCOM",
    "VkPhysicalDeviceShaderOCPMicroscalingTypesFeaturesEXT",
    "VkPhysicalDeviceShaderSplitBarrierFeaturesEXT",
    "VkPhysicalDeviceShaderSplitBarrierPropertiesEXT",
    "VkPhysicalDeviceShaderSubgroupPartitionedFeaturesEXT",
    "VkPhysicalDeviceShaderUniformBufferUnsizedArrayFeaturesEXT",
    "VkPhysicalDeviceSparseImageFormatInfo2",
    "VkPhysicalDeviceTextureCompressionASTC3DFeaturesEXT",
    "VkPhysicalDeviceThrottleHintFeaturesSEC",
    "VkPhysicalDeviceToolProperties",
    "VkPhysicalDeviceVideoEncodeFeedback2FeaturesKHR",
    "VkPhysicalDeviceVulkan11Properties",
    "VkPhysicalDeviceVulkan12Properties",
    "VkPhysicalDeviceVulkan13Properties",
    "VkPhysicalDeviceVulkan14Properties",
    "VkPhysicalDeviceDescriptorBufferFeaturesEXT",
    "VkPhysicalDeviceDescriptorBufferPropertiesEXT",
    "VkPhysicalDeviceAccelerationStructureFeaturesKHR",
    "VkPhysicalDeviceAccelerationStructurePropertiesKHR",
    "VkPhysicalDeviceRayTracingPipelineFeaturesKHR",
    "VkPhysicalDeviceRayTracingPipelinePropertiesKHR",
    "VkPhysicalDeviceRayQueryFeaturesKHR",
    "VkPhysicalDeviceMeshShaderFeaturesEXT",
    "VkPhysicalDeviceMeshShaderPropertiesEXT",
    "VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT",
    "VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT",
    "VkPhysicalDeviceShaderObjectFeaturesEXT",
    "VkPhysicalDeviceShaderObjectPropertiesEXT",
    "VkPhysicalDeviceHostImageCopyFeatures",
    "VkPhysicalDeviceHostImageCopyProperties",
    "VkPhysicalDeviceExtendedDynamicStateFeaturesEXT",
    "VkPhysicalDeviceExtendedDynamicState3FeaturesEXT",
    "VkPhysicalDeviceExtendedDynamicState3PropertiesEXT",
    "VkPhysicalDeviceFragmentShaderBarycentricFeaturesKHR",
    "VkPhysicalDeviceFragmentShaderBarycentricPropertiesKHR",
    "VkPhysicalDeviceFragmentShadingRateFeaturesKHR",
    "VkPhysicalDeviceFragmentShadingRatePropertiesKHR",
    "VkPhysicalDeviceTransformFeedbackFeaturesEXT",
    "VkPhysicalDeviceTransformFeedbackPropertiesEXT",
    "VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT",
    "VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT",
    "VkPhysicalDeviceInlineUniformBlockFeatures",
    "VkPhysicalDeviceInlineUniformBlockProperties",
    "VkPhysicalDevicePrivateDataFeatures",
    "VkPhysicalDeviceSynchronization2Features",
};
inline constexpr std::array<const char*, 104> kValidatedRuntimeQueryGroups = {
    "astc3D",
    "computeOccupancyPriority",
    "cooperativeMatrix",
    "cooperativeMatrixConversion",
    "cooperativeMatrixDecodeVector",
    "core11",
    "core12",
    "core13",
    "core14",
    "dataGraphNeuralAcceleratorStatistics",
    "dataGraphOpticalFlow",
    "descriptorHeap",
    "deviceAddressCommands",
    "deviceFault",
    "elapsedTimerQuery",
    "extendedFlags",
    "external",
    "fifoLatestReady",
    "format2",
    "fragmentDensityMap",
    "fragmentDensityMap2",
    "groups",
    "imageFormat2",
    "imageProcessing3",
    "imageTilingControl",
    "cooperativeMatrixMaintenance1",
    "internallySynchronizedQueues",
    "maintenance10",
    "maintenance11",
    "maintenance7",
    "maintenance8",
    "maintenance9",
    "memory2",
    "multisampledRenderToSwapchain",
    "opacityMicromap",
    "pipelineBinary",
    "pipelineCacheIncrementalMode",
    "presentId2",
    "presentWait2",
    "primitiveRestartIndex",
    "pushConstantBank",
    "queue2",
    "queuePerfHint",
    "shaderAbort",
    "shaderConstantData",
    "shaderInstrumentation",
    "shaderLongVector",
    "shaderMixedFloatDotProduct",
    "shaderMultipleWaitQueues",
    "shaderOcpMicroscalingTypes",
    "shaderSplitBarrier",
    "shaderSubgroupPartitioned",
    "shaderUniformBufferUnsizedArray",
    "sparse",
    "throttleHint",
    "tools",
    "videoEncodeFeedback2",
    "vulkan14",
    "videoCapabilities",
    "descriptorBufferParity",
    "accelerationStructureParity",
    "rayTracingPipelineParity",
    "rayQueryParity",
    "meshShaderParity",
    "graphicsPipelineLibraryParity",
    "shaderObjectParity",
    "hostImageCopyParity",
    "extendedDynamicStateParity",
    "extendedDynamicState3Parity",
    "fragmentShaderBarycentricParity",
    "fragmentShadingRateParity",
    "transformFeedbackParity",
    "vertexAttributeDivisorParity",
    "inlineUniformBlockParity",
    "privateDataParity",
    "synchronization2Parity",
    "caps412SamplerFilterMinmax",
    "caps412DescriptorIndexing",
    "caps412Multiview",
    "caps412Maintenance2",
    "caps412ShaderFloatControls",
    "caps412DepthStencilResolve",
    "caps412ShaderIntegerDotProduct",
    "caps412Maintenance4",
    "caps412SubgroupSizeControl",
    "caps412HostQueryReset",
    "caps412ShaderDemoteToHelperInvocation",
    "caps412PipelineCreationCacheControl",
    "caps412DynamicRendering",
    "caps412ShaderFloat16Int8",
    "caps41216bitStorage",
    "caps412ImagelessFramebuffer",
    "caps412VariablePointers",
    "caps412SamplerYcbcrConversion",
    "caps412ShaderSubgroupExtendedTypes",
    "caps4128bitStorage",
    "caps412ShaderAtomicInt64",
    "caps412TimelineSemaphore",
    "caps412VulkanMemoryModel",
    "caps412ShaderTerminateInvocation",
    "caps412SeparateDepthStencilLayouts",
    "caps412UniformBufferStandardLayout",
    "caps412BufferDeviceAddress",
    "caps412ZeroInitializeWorkgroupMemory",
};
struct QueryDescriptor {
    const char* group;
    const char* scope;
    const char* extension;
    uint32_t minApiMinor;
    const char* queryKind;
};

inline constexpr std::array<QueryDescriptor, 104> kValidatedQueryDescriptors = {{
    {"astc3D", "device-extension", "VK_EXT_texture_compression_astc_3d", 0, "feature+property"},
    {"computeOccupancyPriority", "device-extension", "VK_NV_compute_occupancy_priority", 0, "feature+property"},
    {"cooperativeMatrix", "device-extension", "VK_KHR_cooperative_matrix", 0, "feature+property"},
    {"cooperativeMatrixConversion", "device-extension", "VK_QCOM_cooperative_matrix_conversion", 0, "feature+property"},
    {"cooperativeMatrixDecodeVector", "device-extension", "VK_NV_cooperative_matrix_decode_vector", 0, "feature+property"},
    {"core11", "core", "", 1, "feature+property"},
    {"core12", "core", "", 2, "feature+property"},
    {"core13", "core", "", 3, "feature+property"},
    {"core14", "core", "", 4, "feature+property"},
    {"dataGraphNeuralAcceleratorStatistics", "device-extension", "VK_ARM_data_graph_neural_accelerator_statistics", 0, "feature+property"},
    {"dataGraphOpticalFlow", "device-extension", "VK_ARM_data_graph_optical_flow", 0, "feature-only"},
    {"descriptorHeap", "device-extension", "VK_EXT_descriptor_heap", 0, "feature+property"},
    {"deviceAddressCommands", "device-extension", "VK_KHR_device_address_commands", 0, "feature-only"},
    {"deviceFault", "device-extension", "VK_KHR_device_fault", 0, "feature+property"},
    {"elapsedTimerQuery", "device-extension", "VK_QCOM_elapsed_timer_query", 0, "feature+property"},
    {"extendedFlags", "device-extension", "VK_KHR_extended_flags", 0, "feature-only"},
    {"external", "advanced", "", 0, "physical-device-query"},
    {"fifoLatestReady", "device-extension", "VK_KHR_present_mode_fifo_latest_ready", 0, "feature+property"},
    {"format2", "advanced", "", 0, "physical-device-query"},
    {"fragmentDensityMap", "device-extension", "VK_EXT_fragment_density_map", 0, "feature+property"},
    {"fragmentDensityMap2", "device-extension", "VK_EXT_fragment_density_map2", 0, "feature+property"},
    {"groups", "advanced", "", 0, "physical-device-query"},
    {"imageFormat2", "advanced", "", 0, "physical-device-query"},
    {"imageProcessing3", "device-extension", "VK_QCOM_image_processing3", 0, "feature+property"},
    {"imageTilingControl", "device-extension", "VK_EXT_image_tiling_control", 0, "feature-only"},
    {"cooperativeMatrixMaintenance1", "device-extension", "VK_EXT_cooperative_matrix_maintenance1", 0, "feature+physical-device-query"},
    {"internallySynchronizedQueues", "device-extension", "VK_KHR_internally_synchronized_queues", 0, "feature+property"},
    {"maintenance10", "device-extension", "VK_KHR_maintenance10", 0, "feature+property"},
    {"maintenance11", "device-extension", "VK_KHR_maintenance11", 0, "feature-only"},
    {"maintenance7", "device-extension", "VK_KHR_maintenance7", 0, "feature+property"},
    {"maintenance8", "device-extension", "VK_KHR_maintenance8", 0, "feature+property"},
    {"maintenance9", "device-extension", "VK_KHR_maintenance9", 0, "feature+property"},
    {"memory2", "advanced", "", 0, "physical-device-query"},
    {"multisampledRenderToSwapchain", "device-extension", "VK_EXT_multisampled_render_to_swapchain", 0, "feature+property"},
    {"opacityMicromap", "device-extension", "VK_KHR_opacity_micromap", 0, "feature+property"},
    {"pipelineBinary", "device-extension", "VK_KHR_pipeline_binary", 0, "feature+property"},
    {"pipelineCacheIncrementalMode", "device-extension", "VK_SEC_pipeline_cache_incremental_mode", 0, "feature-only"},
    {"presentId2", "device-extension", "VK_KHR_present_id2", 0, "feature+property"},
    {"presentWait2", "device-extension", "VK_KHR_present_wait2", 0, "feature+property"},
    {"primitiveRestartIndex", "device-extension", "VK_EXT_primitive_restart_index", 0, "feature+property"},
    {"pushConstantBank", "device-extension", "VK_NV_push_constant_bank", 0, "feature+property"},
    {"queue2", "advanced", "", 0, "physical-device-query"},
    {"queuePerfHint", "device-extension", "VK_QCOM_queue_perf_hint", 0, "feature+property"},
    {"shaderAbort", "device-extension", "VK_KHR_shader_abort", 0, "feature+property"},
    {"shaderConstantData", "device-extension", "VK_KHR_shader_constant_data", 0, "feature+property"},
    {"shaderInstrumentation", "device-extension", "VK_ARM_shader_instrumentation", 0, "feature+property"},
    {"shaderLongVector", "device-extension", "VK_EXT_shader_long_vector", 0, "feature+property"},
    {"shaderMixedFloatDotProduct", "device-extension", "VK_VALVE_shader_mixed_float_dot_product", 0, "feature+property"},
    {"shaderMultipleWaitQueues", "device-extension", "VK_QCOM_shader_multiple_wait_queues", 0, "feature+property"},
    {"shaderOcpMicroscalingTypes", "device-extension", "VK_EXT_shader_ocp_microscaling_types", 0, "feature-only"},
    {"shaderSplitBarrier", "device-extension", "VK_EXT_shader_split_barrier", 0, "feature+property"},
    {"shaderSubgroupPartitioned", "device-extension", "VK_EXT_shader_subgroup_partitioned", 0, "feature+property"},
    {"shaderUniformBufferUnsizedArray", "device-extension", "VK_EXT_shader_uniform_buffer_unsized_array", 0, "feature-only"},
    {"sparse", "advanced", "", 0, "physical-device-query"},
    {"throttleHint", "device-extension", "VK_SEC_throttle_hint", 0, "feature+property"},
    {"tools", "advanced", "", 0, "physical-device-query"},
    {"videoEncodeFeedback2", "device-extension", "VK_KHR_video_encode_feedback2", 0, "feature+property"},
    {"videoCapabilities", "advanced", "", 0, "video-profile+capabilities+formats"},
    {"vulkan14", "core", "", 4, "feature+property"},
    {"descriptorBufferParity", "device-extension", "VK_EXT_descriptor_buffer", 0, "feature+property"},
    {"accelerationStructureParity", "device-extension", "VK_KHR_acceleration_structure", 0, "feature+property"},
    {"rayTracingPipelineParity", "device-extension", "VK_KHR_ray_tracing_pipeline", 0, "feature+property"},
    {"rayQueryParity", "device-extension", "VK_KHR_ray_query", 0, "feature-only"},
    {"meshShaderParity", "device-extension", "VK_EXT_mesh_shader", 0, "feature+property"},
    {"graphicsPipelineLibraryParity", "device-extension", "VK_EXT_graphics_pipeline_library", 0, "feature+property"},
    {"shaderObjectParity", "device-extension", "VK_EXT_shader_object", 0, "feature+property"},
    {"hostImageCopyParity", "device-extension", "VK_EXT_host_image_copy", 0, "feature+property"},
    {"extendedDynamicStateParity", "device-extension", "VK_EXT_extended_dynamic_state", 0, "feature-only"},
    {"extendedDynamicState3Parity", "device-extension", "VK_EXT_extended_dynamic_state3", 0, "feature+property"},
    {"fragmentShaderBarycentricParity", "device-extension", "VK_KHR_fragment_shader_barycentric", 0, "feature+property"},
    {"fragmentShadingRateParity", "device-extension", "VK_KHR_fragment_shading_rate", 0, "feature+property"},
    {"transformFeedbackParity", "device-extension", "VK_EXT_transform_feedback", 0, "feature+property"},
    {"vertexAttributeDivisorParity", "device-extension", "VK_EXT_vertex_attribute_divisor", 0, "feature+property"},
    {"inlineUniformBlockParity", "device-extension", "VK_EXT_inline_uniform_block", 0, "feature+property"},
    {"privateDataParity", "device-extension", "VK_EXT_private_data", 0, "feature-only"},
    {"synchronization2Parity", "device-extension", "VK_KHR_synchronization2", 0, "feature-only"},
    {"caps412SamplerFilterMinmax", "device-extension", "VK_EXT_sampler_filter_minmax", 0, "feature+property"},
    {"caps412DescriptorIndexing", "device-extension", "VK_EXT_descriptor_indexing", 0, "feature+property"},
    {"caps412Multiview", "device-extension", "VK_KHR_multiview", 0, "feature+property"},
    {"caps412Maintenance2", "device-extension", "VK_KHR_maintenance2", 0, "feature+property"},
    {"caps412ShaderFloatControls", "device-extension", "VK_KHR_shader_float_controls", 0, "feature+property"},
    {"caps412DepthStencilResolve", "device-extension", "VK_KHR_depth_stencil_resolve", 0, "feature+property"},
    {"caps412ShaderIntegerDotProduct", "device-extension", "VK_KHR_shader_integer_dot_product", 0, "feature+property"},
    {"caps412Maintenance4", "device-extension", "VK_KHR_maintenance4", 0, "feature+property"},
    {"caps412SubgroupSizeControl", "device-extension", "VK_EXT_subgroup_size_control", 0, "feature+property"},
    {"caps412HostQueryReset", "device-extension", "VK_EXT_host_query_reset", 0, "feature+property"},
    {"caps412ShaderDemoteToHelperInvocation", "device-extension", "VK_EXT_shader_demote_to_helper_invocation", 0, "feature+property"},
    {"caps412PipelineCreationCacheControl", "device-extension", "VK_EXT_pipeline_creation_cache_control", 0, "feature+property"},
    {"caps412DynamicRendering", "device-extension", "VK_KHR_dynamic_rendering", 0, "feature+property"},
    {"caps412ShaderFloat16Int8", "device-extension", "VK_KHR_shader_float16_int8", 0, "feature+property"},
    {"caps41216bitStorage", "device-extension", "VK_KHR_16bit_storage", 0, "feature+property"},
    {"caps412ImagelessFramebuffer", "device-extension", "VK_KHR_imageless_framebuffer", 0, "feature+property"},
    {"caps412VariablePointers", "device-extension", "VK_KHR_variable_pointers", 0, "feature+property"},
    {"caps412SamplerYcbcrConversion", "device-extension", "VK_KHR_sampler_ycbcr_conversion", 0, "feature+property"},
    {"caps412ShaderSubgroupExtendedTypes", "device-extension", "VK_KHR_shader_subgroup_extended_types", 0, "feature+property"},
    {"caps4128bitStorage", "device-extension", "VK_KHR_8bit_storage", 0, "feature+property"},
    {"caps412ShaderAtomicInt64", "device-extension", "VK_KHR_shader_atomic_int64", 0, "feature+property"},
    {"caps412TimelineSemaphore", "device-extension", "VK_KHR_timeline_semaphore", 0, "feature+property"},
    {"caps412VulkanMemoryModel", "device-extension", "VK_KHR_vulkan_memory_model", 0, "feature+property"},
    {"caps412ShaderTerminateInvocation", "device-extension", "VK_KHR_shader_terminate_invocation", 0, "feature+property"},
    {"caps412SeparateDepthStencilLayouts", "device-extension", "VK_KHR_separate_depth_stencil_layouts", 0, "feature+property"},
    {"caps412UniformBufferStandardLayout", "device-extension", "VK_KHR_uniform_buffer_standard_layout", 0, "feature+property"},
    {"caps412BufferDeviceAddress", "device-extension", "VK_KHR_buffer_device_address", 0, "feature+property"},
    {"caps412ZeroInitializeWorkgroupMemory", "device-extension", "VK_KHR_zero_initialize_workgroup_memory", 0, "feature+property"},
}};

constexpr const QueryDescriptor* findQueryDescriptor(const char* group) {
    if (!group) return nullptr;
    for (const auto& descriptor : kValidatedQueryDescriptors) {
        if (std::strcmp(descriptor.group, group) == 0) return &descriptor;
    }
    return nullptr;
}

inline constexpr std::array<const char*, 10> kInstanceDependencyCandidates = {
    "VK_KHR_get_physical_device_properties2",
    "VK_KHR_get_surface_capabilities2",
    "VK_KHR_device_group_creation",
    "VK_KHR_external_memory_capabilities",
    "VK_KHR_external_semaphore_capabilities",
    "VK_KHR_external_fence_capabilities",
    "VK_KHR_display",
    "VK_KHR_get_display_properties2",
    "VK_EXT_debug_utils",
    "VK_EXT_debug_report",
};

}
